# Generated by Django 6.0.3 on 2026-03-23 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='respuestaencuesta',
            unique_together=set(),
        ),
    ]
