# Generated by Django 4.2.9 on 2026-06-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0004_respuestaencuesta_nivel_riesgo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestaencuesta',
            name='puntaje_normalizado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Puntaje normalizado 0-100', max_digits=5, null=True),
        ),
    ]
