# Generated by Django 4.2.9 on 2026-06-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0005_respuestaencuesta_puntaje_normalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='tipo_puntuacion',
            field=models.CharField(choices=[('directa', 'Directa'), ('invertida', 'Invertida')], default='directa', help_text='Directa: Siempre=4, Nunca=0. Invertida: Siempre=0, Nunca=4', max_length=10),
        ),
    ]
