# Generated by Django 4.2.9 on 2026-06-26 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0006_pregunta_tipo_puntuacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuestapregunta',
            name='opcion_seleccionada',
        ),
        migrations.DeleteModel(
            name='OpcionRespuesta',
        ),
    ]
