# Generated by Django 4.2.9 on 2026-06-26 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='departamento',
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
    ]
