# Generated by Django 6.0.3 on 2026-07-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='departamento',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='empleado',
            name='edad',
            field=models.CharField(blank=True, choices=[('15-19', '15 - 19'), ('20-24', '20 - 24'), ('25-29', '25 - 29'), ('30-34', '30 - 34'), ('35-39', '35 - 39'), ('40-44', '40 - 44'), ('45-49', '45 - 49'), ('50-54', '50 - 54'), ('55-59', '55 - 59'), ('60-64', '60 - 64'), ('65-69', '65 - 69'), ('70+', '70 o más')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='empleado',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('casado', 'Casado'), ('divorciado', 'Divorciado'), ('soltero', 'Soltero'), ('viudo', 'Viudo'), ('union_libre', 'Unión libre')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='empleado',
            name='nivel_estudios',
            field=models.CharField(blank=True, choices=[('sin_formacion', 'Sin formación'), ('primaria_terminada', 'Primaria Terminada'), ('primaria_incompleta', 'Primaria Incompleta'), ('secundaria_terminada', 'Secundaria Terminada'), ('secundaria_incompleta', 'Secundaria Incompleta'), ('preparatoria_terminada', 'Preparatoria o Bachillerato Terminada'), ('preparatoria_incompleta', 'Preparatoria o Bachillerato Incompleta'), ('tecnico_terminada', 'Técnico Superior Terminada'), ('tecnico_incompleta', 'Técnico Superior Incompleta'), ('licenciatura_terminada', 'Licenciatura Terminada'), ('licenciatura_incompleta', 'Licenciatura Incompleta'), ('maestria_terminada', 'Maestría Terminada'), ('maestria_incompleta', 'Maestría Incompleta'), ('doctorado_terminada', 'Doctorado Terminada'), ('doctorado_incompleta', 'Doctorado Incompleta')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='empleado',
            name='ocupacion',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='empleado',
            name='rotacion_turnos',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='empleado',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tiempo_experiencia',
            field=models.CharField(blank=True, choices=[('menos_6m', 'Menos de 6 meses'), ('6m_1a', 'Entre 6 meses y 1 año'), ('1_4a', 'Entre 1 a 4 años'), ('5_9a', 'Entre 5 a 9 años'), ('10_14a', 'Entre 10 a 14 años'), ('15_19a', 'Entre 15 a 19 años'), ('20_24a', 'Entre 20 a 24 años'), ('25a+', '25 años o más')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tiempo_puesto_actual',
            field=models.CharField(blank=True, choices=[('menos_6m', 'Menos de 6 meses'), ('6m_1a', 'Entre 6 meses y 1 año'), ('1_4a', 'Entre 1 a 4 años'), ('5_9a', 'Entre 5 a 9 años'), ('10_14a', 'Entre 10 a 14 años'), ('15_19a', 'Entre 15 a 19 años'), ('20_24a', 'Entre 20 a 24 años'), ('25a+', '25 años o más')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_contratacion',
            field=models.CharField(blank=True, choices=[('obra_proyecto', 'Por obra o proyecto'), ('indeterminado', 'Tiempo indeterminado'), ('determinado', 'Por tiempo determinado (temporal)'), ('honorarios', 'Honorarios')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_jornada',
            field=models.CharField(blank=True, choices=[('nocturno', 'Fijo nocturno (entre las 20:00 y 6:00 hrs)'), ('mixto', 'Fijo mixto (combinación de nocturno y diurno)'), ('diurno', 'Fijo diurno (entre las 6:00 y 20:00 hrs)')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_personal',
            field=models.CharField(blank=True, choices=[('sindicalizado', 'Sindicalizado'), ('confianza', 'Confianza'), ('ninguno', 'Ninguno')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_puesto',
            field=models.CharField(blank=True, choices=[('operativo', 'Operativo'), ('supervisor', 'Supervisor'), ('profesional', 'Profesional o técnico'), ('gerente', 'Gerente')], default='', max_length=20),
        ),
    ]
