# Generated by Django 6.0.3 on 2026-07-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_empleado_datos_cuestionario1'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='accidente_grave',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='empleado',
            name='actos_violentos',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='empleado',
            name='amenazas',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='empleado',
            name='asalto',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='empleado',
            name='dificultad_concentrarse',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='empleado',
            name='dificultad_dormir',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='empleado',
            name='dificultad_expresar_sentimientos',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='empleado',
            name='dificultad_recordar_evento',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='empleado',
            name='disminuye_interes_actividades',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='empleado',
            name='evitar_actividades_lugares_personas',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='empleado',
            name='evitar_sentimientos_conversaciones',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='empleado',
            name='irritable_arranos_coraje',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='empleado',
            name='nervioso_alerta',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='empleado',
            name='otro_riesgo_vida_salud',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='empleado',
            name='recuerdos_recurrentes_malestar',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='empleado',
            name='secuestro',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='empleado',
            name='sensacion_alejamiento',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='empleado',
            name='sobresalta_facilmente',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='empleado',
            name='suenos_recurrentes_malestar',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='empleado',
            name='vida_futuro_limitado',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], default='', max_length=2),
        ),
    ]
