# Generated by Django 6.0.3 on 2026-07-04 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_cuestionario1_secciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudResetPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('atendida', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Reset de Contraseña',
                'verbose_name_plural': 'Solicitudes de Reset de Contraseña',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
