# Generated by Django 4.2.9 on 2026-03-10 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encuestas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestaencuesta',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_encuestas', to='usuarios.empleado'),
        ),
        migrations.AddField(
            model_name='respuestaencuesta',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='encuestas.encuesta'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='encuestas.encuesta'),
        ),
        migrations.AddField(
            model_name='opcionrespuesta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='encuestas.pregunta'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encuestas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accesoencuesta',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos_encuestas', to='usuarios.empleado'),
        ),
        migrations.AddField(
            model_name='accesoencuesta',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos', to='encuestas.encuesta'),
        ),
        migrations.AlterUniqueTogether(
            name='respuestapregunta',
            unique_together={('respuesta_encuesta', 'pregunta')},
        ),
        migrations.AlterUniqueTogether(
            name='respuestaencuesta',
            unique_together={('encuesta', 'empleado')},
        ),
        migrations.AlterUniqueTogether(
            name='pregunta',
            unique_together={('encuesta', 'orden')},
        ),
        migrations.AlterUniqueTogether(
            name='accesoencuesta',
            unique_together={('encuesta', 'empleado')},
        ),
    ]
