# Generated by Django 4.2.9 on 2026-06-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0003_alter_respuestaencuesta_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestaencuesta',
            name='nivel_riesgo',
            field=models.CharField(blank=True, choices=[('nulo', 'Nulo'), ('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('muy_alto', 'Muy Alto')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='respuestaencuesta',
            name='puntaje_condiciones_trabajo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Puntaje de las 30 preguntas de condiciones de trabajo', max_digits=5, null=True),
        ),
    ]
